id: IC444E734
legacy_id: P000519
ocr_import_info:
  bdrc_scan_id: W1KG12536
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T18:38:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:32:54.501586+00:00'
last_modified: 2022-08-31 11:33:27.666985
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12536
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12536
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་མང་།
statistics:
  ocr_word_mean_confidence_index: 0.7436869609106513
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1KG12588:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12588
      total_pages: 756
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG12588.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.73661736311152
    legacy_id: v002
  I1KG12584:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12584
      total_pages: 756
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12584.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7506026804292518
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
